version: '3.8'

services:
  dev-db:
    image: postgres:latest
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: db